In [144]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
iris=pd.read_csv("/home/pshankar/Documents/Iris_Data_analysis/Iris.csv")


In [4]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
iris['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

In [8]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
#split the data set for train and test
X = iris.drop('Species',axis=1)
y = iris['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


Classification of Iris dataset using different classification Algorithm 

In [126]:
#Logistic Regression
logreg=LogisticRegression()
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)
#print(X_test[0:5])
#print(y_pred[0:5])
print(confusion_matrix(y_pred,y_test))
print('accuracy is',accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[11  0  0]
 [ 0 11  0]
 [ 0  2  6]]
accuracy is 0.9333333333333333
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.85      1.00      0.92        11
 Iris-virginica       1.00      0.75      0.86         8

    avg / total       0.94      0.93      0.93        30



In [152]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)
y_pred =dtc.predict(X_test)
print('accuracy is',accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

accuracy is 0.9666666666666667
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.93      0.96        14
 Iris-virginica       0.83      1.00      0.91         5

    avg / total       0.97      0.97      0.97        30



In [128]:
#naive bayes 
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)
y_pred=nb.predict(X_test)
print('accuracy ',accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

accuracy  1.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30



In [129]:
#Support Vector Machine
from sklearn.svm import LinearSVC
sv=LinearSVC()
sv.fit(X_train,y_train)
y_pred=sv.predict(X_test)
print('accuracy ',accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

accuracy  0.9333333333333333
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.87      0.93        15
 Iris-virginica       0.67      1.00      0.80         4

    avg / total       0.96      0.93      0.94        30



In [130]:
# K-Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print('accuracy ',accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

accuracy  1.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30



In [146]:
print("logistc regression ")
print(cross_val_score(logreg,X_train,y_train,scoring='accuracy',cv=10).mean() *100)

logistc regression 
92.75641025641026


In [153]:
print("decision tree classification ")
print(cross_val_score(dtc,X_train,y_train,scoring='accuracy',cv=10).mean() *100)

decision tree classification 
99.23076923076923


In [154]:
print("naive bayes ")
print(cross_val_score(nb,X_train,y_train,scoring='accuracy',cv=10).mean() *100)

naive bayes 
99.23076923076923


In [150]:
print("support vector machine  ")
print(cross_val_score(sv,X_train,y_train,scoring='accuracy',cv=10).mean() *100)

support vector machine  
83.74825174825176


In [151]:
print("k nearest neighbours ")
print(cross_val_score(knn,X_train,y_train,scoring='accuracy',cv=10).mean() *100)

k nearest neighbours 
98.3974358974359


From the above cross validation test and accuracy score we can use the "naive bayes model " for classification of flower.